import os
from dotenv import load_dotenv
from github import Github

load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO = os.getenv("GITHUB_REPO")


def open_fix_pull_request(branch_name: str, root_cause: str, explanation: str, stack_trace: str):
    """
    Opens a pull request from the given fix branch into the repo's
    default branch, with a clear description for a human reviewer.
    GitHub automatically renders the code diff — we don't need to build that.
    """
    client = Github(GITHUB_TOKEN)
    repo = client.get_repo(GITHUB_REPO)

    default_branch = repo.default_branch

    pr_title = f"Auto-fix: {root_cause[:60]}"

    pr_body = f"""### Root Cause
{root_cause}

### What Changed
{explanation}

<details>
<summary>Original stack trace</summary>

</details>

_This fix was automatically generated by the Cloud Log Auditor agent._
"""

    pull_request = repo.create_pull(
        title=pr_title,
        body=pr_body,
        head=branch_name,
        base=default_branch,
    )

    return pull_request.html_url


if __name__ == "__main__":
    from logs import get_latest_error_log
    from github_fetch import get_buggy_code
    from diagnose import diagnose_bug
    from extract_fix import extract_fixed_code, extract_root_cause_and_explanation
    from create_fix_branch import create_branch_with_fix

    latest_log = get_latest_error_log()
    code = get_buggy_code()
    result = diagnose_bug(
        stack_trace=latest_log.get("stack_trace"),
        code=code,
        filename=os.getenv("TARGET_FILE"),
    )
    fixed_code = extract_fixed_code(result)
    root_cause, explanation = extract_root_cause_and_explanation(result)

    branch_name = create_branch_with_fix(fixed_code)

    pr_url = open_fix_pull_request(
        branch_name=branch_name,
        root_cause=root_cause,
        explanation=explanation,
        stack_trace=latest_log.get("stack_trace"),
    )

    print("Pull request created:", pr_url)